### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by nvdcmptr** [obfuscator-llvm/obfuscator#19]
please put release files in repository.

**Comment by pyknite** [comment]
Hi,

This repository is for source files only, I already sent you the binaries in private.

**Comment by nvdcmptr** [comment]
I can not download binaries. where is binaries?

**Comment by mbazaliy** [comment]
Check installation wiki

**Comment by nvdcmptr** [comment]
tnx "mbazaliy". bu i check it before babe

**Comment by pyknite** [comment]
@nvdcmptr I sent you an e-mail the 07.01.2015 with a temporary link to download the binaries. This link is not valid anymore. I can send a new one to you tonite.

Otherwise, as I said before to you, just get the latest branch: git clone -b llvm-3.5 https://github.com/obfuscator-llvm/obfuscator.git

This one compile fine on OSX...

**Comment by nvdcmptr** [comment]
tnx "pyknite".
that link you send me was corrupted(i think). because i could not download that file when it was valid.
if you can please try another file host.
excuse me for annoyance
