### ISSUE TITLE
LLVM 3.6

### ISSUE THREAD

**Issue by paulshapiro** [obfuscator-llvm/obfuscator#22]
Hello!

Any plans to update obfuscator-llvm to support LLVM 3.6, which was released on Feb 27, 2015?

Thanks,
Paul

**Comment by pyknite** [comment]
Hi,

Sorry for the delay... We will do it, but not  right now.

Cheers

**Comment by ivkim** [comment]
Would this account for this error when trying to compile? (Running llvm3.5 branch on Xcode 6.3.2 - llvm3.6)

clang-3.5: error: unknown argument: '-fbuild-session-file=/Users/asdf/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation'
clang-3.5: error: option '-fmodules-validate-once-per-build-session' requires '-fbuild-session-timestamp=<seconds since Epoch>'

**Comment by pyknite** [comment]
It seems that '-fbuild-session-file' replaces '-fbuild-session-timestamp=' in 3.6.
We will push the 3.6 version soon.

**Comment by thinkwing** [comment]
How about the progress of the 3.6 version?

**Comment by pyknite** [comment]
Since I will not be at work for the next two weeks, I would say in 3 weeks (maybe before, if I have the time). Definitely before the end of june.

**Comment by rockygsm** [comment]
Hello any plan to add string encryption -mllvm -xse ?

**Comment by LarryLee** [comment]
clang-3.5: error: unknown argument: '-fbuild-session-file=/Users/***/DerivedData/ModuleCache/Session.modulevalidation'
clang-3.5: error: unknown argument: '-fapplication-extension'
clang-3.5: error: option '-fmodules-validate-once-per-build-session' requires '-fbuild-session-timestamp=<seconds since Epoch>'
Command /Users/***/WorkSpace/script/build/bin/clang-3.5 failed with exit code 1

I got the same problem . What should I do next ? Thanks.

**Comment by LarryLee** [comment]
I got this error
Command /Users/larry/WorkSpace/script/build/bin/clang failed with exit code 1

"ExecPath = "clang"; -> ExecPath = "/path/to/obfuscator_bin/clang";" Is this right?

**Comment by ivkim** [comment]
do you think you'll still hit end of june time frame?

**Comment by pyknite** [comment]
Im' working on a bug... I hope so.

**Comment by pyknite** [comment]
Just pushed 3.6.1
