### ISSUE TITLE
Cannot compile C++ code with Obfuscator-LLVM

### ISSUE THREAD

**Issue by riless** [obfuscator-llvm/obfuscator#59]
I've followed the [installation instructions](https://github.com/obfuscator-llvm/obfuscator/wiki/Installation) and successfully build obfuscator-llvm.

The tool is perfectly working with c code, but seems to not support c++ code.

```
// main.c
#include <iostream>
using namespace std;

int main(){
	std::cout << "Hello World\n";
	return 0;
}

$ /path/to/clang++ main.cc
main.cc:2:10: fatal error: 'iostream' file not found
#include <iostream>
         ^
1 error generated.

```
The clang++ and clang files in build/bin/ are just symlinks to clang-3.6.

I've found in the [FAQ](https://github.com/obfuscator-llvm/obfuscator/wiki/FAQ) this question: 

> Which programming languages are supported by Obfuscator-LLVM?
> 
> The Clang front-end supports C, C++, Objective-C and Objective-C++. Additionally, one can use LLVM as a GCC back-end through the DragonEgg plugin. DragonEgg fully supports Ada, C, C++ and Fortran and it has partial support for Go, Java, Objective-C as well as Objective-C++.

Where can I found the C++ version of that compiler ?

**Comment by AnomalRoil** [comment]
This is strange, I've also recently compiled it and it worked fine with C++ code. Note that I'm just an user, but I still want to try and help you: it looks like you may suffer from multiple issues, in my opinion. 

First issue: you named your file `main.c` but since it is C++, it should be called `main.cpp`, if you tried compiling with your own g++ ou clang++, didn't it complained about treating C input as C++ when in C++ mode?

Now regarding the error message, which branch did you checkout and what clang version do you have on your system? 
This message usually means the C++ standard library headers are not available. 
If it is Clang 3.3, you may want to try with another one, like the 3.6.1 since this problem is a [known problem](https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-3.3/+bug/1243725/) (for Ubuntu at least) with 3.3. If you are on OSX, you may want to try with the `clang-425.0.24` one I guess.
Also, did you try providing the path to the headers to clang using `-i /path-to-std-headers` and did it still fail?

Regarding the binary, you should be using the clang++ symlink in the /path/to/obfuscator/build/bin directory. 

Finally, note that with the code you are testing, you won't see any difference between the output of your clang++ and the obfuscator's one, since you are not having loops, branches and stuff like that, try adding an if condition in your code, it will allow you to see the difference. (Or test with [the example provided](https://github.com/obfuscator-llvm/obfuscator/wiki/Control-Flow-Flattening) regarding the flattening.)

_Voilà_, just my two cents, I hope it helps you. My trials on Ubuntu 16.04 and comparing it with clang out of the repo were working just fine.
